from dataclasses import dataclass

# ruff: noqa: N815


@dataclass(frozen=True)
class MET:
    FSS: str = "FSS"
    ME: str = "ME"
    PODY: str = "PODY"
    RMSE: str = "RMSE"
    cnt: str = "cnt"
    cts: str = "cts"
    nbrcnt: str = "nbrcnt"
    FULL: str = "FULL"
    BOTH: str = "BOTH"
    nbrhd: str = "nbrhd"
    fcst: str = "fcst"
    field: str = "field"
    mask: str = "mask"
    grid: str = "grid"
    model: str = "model"
    nc_pairs_flag: str = "nc_pairs_flag"
    obs: str = "obs"
    obtype: str = "obtype"
    output_flag: str = "output_flag"
    output_prefix: str = "output_prefix"
    regrid: str = "regrid"
    method: str = "method"
    to_grid: str = "to_grid"
    tmp_dir: str = "tmp_dir"


@dataclass(frozen=True)
class S:
    GFS: str = "GFS"
    HRRR: str = "HRRR"
    OBS: str = "OBS"
    PREPBUFR: str = "PREPBUFR"
    atmosphere: str = "atmosphere"
    baseline: str = "baseline"
    coords: str = "coords"
    cycle: str = "cycle"
    cycles: str = "cycles"
    env: str = "env"
    fh: str = "fh"
    firstbyte: str = "firstbyte"
    forecast: str = "forecast"
    forecast_reference_time: str = "forecast_reference_time"
    grid: str = "grid"
    grids: str = "grids"
    grids_baseline: str = "grids_baseline"
    grids_forecast: str = "grids_forecast"
    grids_truth: str = "grids_truth"
    heightAboveGround: str = "heightAboveGround"
    hh: str = "hh"
    inittime: str = "inittime"
    isobaricInhPa: str = "isobaricInhPa"
    lastbyte: str = "lastbyte"
    latitude: str = "latitude"
    leadtime: str = "leadtime"
    leadtimes: str = "leadtimes"
    level: str = "level"
    level_type: str = "level_type"
    levels: str = "levels"
    longitude: str = "longitude"
    mask: str = "mask"
    method: str = "method"
    name: str = "name"
    obs: str = "obs"
    path: str = "path"
    paths: str = "paths"
    point: str = "point"
    pool: str = "pool"
    proj: str = "proj"
    projection: str = "projection"
    properties: str = "properties"
    regrid: str = "regrid"
    run: str = "run"
    session: str = "session"
    start: str = "start"
    step: str = "step"
    stop: str = "stop"
    surface: str = "surface"
    time: str = "time"
    to: str = "to"
    truth: str = "truth"
    type: str = "type"
    url: str = "url"
    validtime: str = "validtime"
    variables: str = "variables"
    yyyymmdd: str = "yyyymmdd"
