from dataclasses import dataclass


@dataclass(frozen=True)
class S:
    GFS: str = "GFS"
    HRRR: str = "HRRR"
    OBS: str = "OBS"
    PREPBUFR: str = "PREPBUFR"
    baseline: str = "baseline"
    coords: str = "coords"
    cycles: str = "cycles"
    firstbyte: str = "firstbyte"
    forecast: str = "forecast"
    forecast_reference_time: str = "forecast_reference_time"
    grids: str = "grids"
    grids_baseline: str = "grids_baseline"
    grids_forecast: str = "grids_forecast"
    grids_truth: str = "grids_truth"
    lastbyte: str = "lastbyte"
    latitude: str = "latitude"
    leadtimes: str = "leadtimes"
    level: str = "level"
    level_type: str = "level_type"
    levels: str = "levels"
    longitude: str = "longitude"
    mask: str = "mask"
    method: str = "method"
    name: str = "name"
    obs: str = "obs"
    path: str = "path"
    paths: str = "paths"
    proj: str = "proj"
    projection: str = "projection"
    properties: str = "properties"
    regrid: str = "regrid"
    run: str = "run"
    session: str = "session"
    start: str = "start"
    step: str = "step"
    stop: str = "stop"
    time: str = "time"
    to: str = "to"
    truth: str = "truth"
    type: str = "type"
    url: str = "url"
    variables: str = "variables"
